# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.CharField(max_length=15)),
                ('Address', models.TextField(max_length=500)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=60)),
                ('Car_plate_number', models.CharField(max_length=80)),
                ('Reg_ID', models.CharField(max_length=60)),
                ('file_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=4)),
                ('First_Name', models.CharField(max_length=60)),
                ('Last_Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.User'),
        ),
    ]
